### ISSUE TITLE
Uncaught MemoryError


### ISSUE THREAD

**Issue by kankonaj** [Geoalert/mapflow-qgis#42]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\Users/kanko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mapflow\mapflow.py", line 1168, in calculate_aoi_area_polygon_layer
    aoi = QgsGeometry.collectGeometry([feature.geometry() for feature in features])
  File "C:\Users/kanko/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mapflow\mapflow.py", line 1168, in <listcomp>
    aoi = QgsGeometry.collectGeometry([feature.geometry() for feature in features])
MemoryError

```
mapflow 1.7.0, QGIS 3.26.3-Buenos Aires on Windows 10

**Comment by Ziheng56** [comment]
KeyError: '' 
Traceback (most recent call last):
  File "C:\Users/王想/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mapflow\mapflow.py", line 1499, in create_processing
    provider = self.providers[raster_option]
KeyError: ''


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, f186b8efe0e
